# -*- mode: ruby -*-
# vi: set ft=ruby :

# This vagrantfile creates a VM with the development environment
# configured and ready to go.
#
# The setup script (env var $script) in this file installs docker.
# This is not in the setup.sh file because the docker install needs
# to be secure when running on a real linux machine.
# The docker environment that is installed by this script is not secure,
# it depends on the host being secure.
#
# At the end of the setup script in this file, a call is made
# to run setup.sh to create the developer environment.

# This is the mount point for the sync_folders of the source
ROOT_DIR = "/src"
PRJ_DIR = "/project"

$dev_script = <<SCRIPT
set -x

cd /project/devenv/scripts

chmod a+x *.sh

./install_basic.sh

#./all_steps.sh

SCRIPT

Vagrant.require_version ">= 2.0.0"
Vagrant.configure('2') do |config|

  config.vm.boot_timeout = 1000

  config.vm.synced_folder "../../", "#{ROOT_DIR}"
  config.vm.synced_folder "../", "#{PRJ_DIR}"

  config.vm.define "cg_dapp_dev", primary: true do |cg_dapp_dev|
    cg_dapp_dev.vm.box = "ubuntu/xenial64"
    cg_dapp_dev.vm.provision :shell, inline: $dev_script

    cg_dapp_dev.vm.network "public_network"

    #cg_dapp_dev.vm.network :forwarded_port, guest: 80, host: 38080

    cg_dapp_dev.ssh.username = "vagrant"
    #dev.ssh.password = "vagrant"

    cg_dapp_dev.vm.provider :virtualbox do |vb|
      vb.name = "cg_dapp_dev"
      vb.customize ['modifyvm', :id, '--memory', '4096']
      vb.cpus = 2
    end
  end

end
