apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: ""
    field.cattle.io/publicEndpoints: '[{"port":31099,"protocol":"TCP","serviceName":"default:cg-dapp-stg-nodeport","allNodes":true}]'
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-cg-dapp-stg
  name: cg-dapp-stg
  namespace: cg-dapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-cg-dapp-stg
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"cg-dapp-stg-nodeport","kind":"NodePort","name":"80tcp310991","protocol":"TCP","sourcePort":31099}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-cg-dapp-stg
    spec:
      containers:
      - image: repo.luomutrip.com:8089/cg-dapp-stg:v1
        imagePullPolicy: Always
        name: cg-dapp-stg
        ports:
        - containerPort: 80
          name: 80tcp310991
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nexus-acar
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
